name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    services:
      sqlserver:
        image: mcr.microsoft.com/mssql/server:2019-latest
        ports:
          - 1433:1433
        env:
          SA_PASSWORD: "@Hackathon2025"
          ACCEPT_EULA: "Y"

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 8.0.x

      - name: Install Dependencies
        run: dotnet restore "HKTHealthMed/HKTHealthMed/PROJ_HealthMed/PROJ_HealthMed/PROJ_HealthMed.csproj"

      - name: Build
        run: dotnet build "HKTHealthMed/HKTHealthMed/PROJ_HealthMed/PROJ_HealthMed/PROJ_HealthMed.csproj" --configuration Release --no-restore

      - name: Run Tests
        run: dotnet test "HKTHealthMed/HKTHealthMed/PROJ_HealthMed/PROJ_HealthMed/PROJ_HealthMed.csproj" --no-restore --verbosity normal

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: giulianojunior/HKTHealthMed:latest
